# Generated by Django 4.2.15 on 2024-08-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='EngineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='RepairingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SteeringAxleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(default='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleNumber', models.TextField()),
                ('engineNumber', models.TextField()),
                ('transmissionNumber', models.TextField()),
                ('driveAxleNumber', models.TextField()),
                ('steeringAxleNumber', models.TextField()),
                ('deliveryContract_number_date', models.TextField()),
                ('shipmentDate', models.DateField()),
                ('consignee', models.TextField()),
                ('deliveryAddress', models.TextField()),
                ('equipment', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('driveAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.driveaxlemodel')),
                ('engineModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.enginemodel')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
                ('steeringAxleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.steeringaxlemodel')),
                ('transmissionModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.transmissionmodel')),
                ('vehicleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('workOrderNumber', models.TextField()),
                ('workOrderDate', models.DateField()),
                ('maintenanceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancecompany')),
                ('maintenanceType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancetype')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimDate', models.DateField()),
                ('operatingTime', models.IntegerField()),
                ('failureDescription', models.TextField()),
                ('usedSpareParts', models.TextField()),
                ('repairingDate', models.DateField()),
                ('vehicleDowntime', models.IntegerField()),
                ('failureNode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.failurenode')),
                ('repairingMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.repairingmethod')),
                ('serviceCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehicle')),
            ],
        ),
    ]
