# Generated by Django 4.2.15 on 2024-08-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='failureDescription',
            field=models.TextField(default='описание'),
        ),
    ]
