# Generated by Django 4.2.15 on 2024-08-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0002_alter_claims_failuredescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='deliveryContract_number_date',
            field=models.TextField(default='номер договора, дата'),
        ),
    ]
