# Generated by Django 4.2.15 on 2024-08-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0003_alter_vehicle_deliverycontract_number_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='serviceCompany',
        ),
    ]
