# Generated by Django 4.2.15 on 2024-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant_app', '0004_remove_maintenance_servicecompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleNumber',
            field=models.TextField(verbose_name='Зав. № машины'),
        ),
    ]
