# Generated by Django 4.2.15 on 2024-08-26 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('silant_app', '0005_alter_vehicle_vehiclenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='claimDate',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='failureDescription',
            field=models.TextField(default='описание', verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='failureNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.failurenode', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='operatingTime',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='repairingDate',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='repairingMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.repairingmethod', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Cервисная компания'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='usedSpareParts',
            field=models.TextField(verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehicle', verbose_name='Mашина'),
        ),
        migrations.AlterField(
            model_name='claims',
            name='vehicleDowntime',
            field=models.IntegerField(verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancecompany', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceDate',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenanceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.maintenancetype', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operatingTime',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehicle', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='workOrderDate',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='workOrderNumber',
            field=models.TextField(verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='consignee',
            field=models.TextField(verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deliveryAddress',
            field=models.TextField(verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deliveryContract_number_date',
            field=models.TextField(default='номер договора, дата', verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driveAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.driveaxlemodel', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driveAxleNumber',
            field=models.TextField(verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engineModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.enginemodel', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engineNumber',
            field=models.TextField(verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='equipment',
            field=models.TextField(verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.servicecompany', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='shipmentDate',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steeringAxleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.steeringaxlemodel', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steeringAxleNumber',
            field=models.TextField(verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmissionModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.transmissionmodel', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmissionNumber',
            field=models.TextField(verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silant_app.vehiclemodel', verbose_name='Модель техники'),
        ),
    ]
