# Generated by Django 4.2.15 on 2024-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('MA', 'Manager'), ('CL', 'Client'), ('SC', 'Service Company')], max_length=15),
        ),
    ]
