# Generated by Django 4.2.15 on 2024-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Client', 'Client'), ('Service Company', 'Service Company')], max_length=15),
        ),
    ]
